STEAMCONTROLLER_NO_SWIZZLING and TestApp update.
zydeco/SteamController pull request #7
Opened 2020-04-21 17:37 UTC by ToddLa

added STEAMCONTROLLER_NO_SWIZZLING build options.
made the TestApp work with GCControllers and SteamControllers.

2020-07-05 12:48 UTC, zydeco requested changes
thanks for your contribution!

please remove the defines so the options aren't always enabled

2020-07-05 12:48 UTC, zydeco commented on SteamController/SteamControllerManager.h
> +
```suggestion
```

don't enable these options by default, it should be possible to enable/disable them in build settings so it works with the `no-private-api` pod subspec

2020-07-05 17:32 UTC, ToddLa commented
Ok will do! I will also do it in PR #8 too. (You should look at just taking #8)

2020-07-05 18:38 UTC, ToddLa commented
I updated PR #7 and PR #8

2021-08-03 17:18 UTC, zydeco commented
Closing this since it was merged in #8

2021-08-03 17:18 UTC, closed without merging